Update simple

diff --git a/simple-0.1/usr/sbin/simple b/simple-0.1/usr/sbin/simple
--- a/simple-0.1/usr/sbin/simple
+++ b/simple-0.1/usr/sbin/simple
@@ -3,10 +3,11 @@
 sourcing(){
 ######-path-#########
 if [ -d /tools ]; then
-    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin:/tools/sbin
+	PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin:/tools/sbin
 else
-    PATH=/bin:/usr/bin:/sbin:/usr/sbin
+	PATH=/bin:/usr/bin:/sbin:/usr/sbin
 fi
+
 #default dir variables
 ETC_DIR="/etc/simple"
 
@@ -15,18 +16,22 @@ get_var_file "$ETC_DIR/make.conf"
 
 # where is placed buildme files
 if [[ -z "$BUILDME_DIR" ]]; then
-    BUILDME_DIR="/var/cache/simple/buildme"
+	BUILDME_DIR="/var/cache/simple/buildme"
 fi
+
 # where is placed downloaded files
 if [[ -z "$DISTDIR" ]]; then
-    DISTDIR="/var/cache/simple/distfiles"
+	DISTDIR="/var/cache/simple/distfiles"
 fi
+
 # place for upacked files to build (HOME for simple user) (like ${SIMPLEBUILD_DIR}/${CATEGORY}/${PACKAGE} )
 SIMPLEBUILD_DIR="/var/tmp/simple"
+
 # be sure bashrc deleted from previous run
 if [ -f $SIMPLEBUILD_DIR/bashrc ]; then
-    rm -f $SIMPLEBUILD_DIR/bashrc
+	rm -f $SIMPLEBUILD_DIR/bashrc
 fi
+
 add_variable PATH ETC_DIR BUILDME_DIR DISTDIR SIMPLEBUILD_DIR
 add_variable CFLAGS CXXFLAGS CPPFLAGS LDFLAGS MAKEFLAGS STABILITY LINGUAS USE
 
@@ -45,46 +50,46 @@ BASH_ENV="$SIMPLEBUILD_DIR/bashrc" su simple -s /bin/bash /usr/lib/simple/fetch
 run_all_build(){
 source $SIMPLEBUILD_DIR/bashrc
 for CPV in ${USERLIST_TO_INSTALL[@]}; do
-    BASH_ENV="$SIMPLEBUILD_DIR/bashrc" su simple -s /bin/bash /usr/lib/simple/all_build -- $CPV -setup_env
+	BASH_ENV="$SIMPLEBUILD_DIR/bashrc" su simple -s /bin/bash /usr/lib/simple/all_build -- $CPV -setup_env
 
-    # Checking if previous source is present and delete
-    # DANGEROUS operation. Check if prefix of path is /var/tmp/simple to allow this
-    broot=$(grep BROOT $SIMPLEBUILD_DIR/bashrc | sed -nr 's/BROOT="([^"]*?)(")/\1/p')
+	# Checking if previous source is present and delete	
+	# DANGEROUS operation. Check if prefix of path is /var/tmp/simple to allow this
+	broot=$(grep BROOT $SIMPLEBUILD_DIR/bashrc | sed -nr 's/BROOT="([^"]*?)(")/\1/p')
 
-    if [ -d "$broot" ]; then
-        path_regex="("$SIMPLEBUILD_DIR")(/)([-a-z]+)(/)([-_a-z0-9.]+)"
+	if [ -d "$broot" ]; then
+		path_regex="("$SIMPLEBUILD_DIR")(/)([-a-z]+)(/)([-_a-z0-9.]+)"
 
-        if [[ "$broot" =~ $(echo "$path_regex") ]]; then
-            if [ "${BASH_REMATCH[1]}" != "$SIMPLEBUILD_DIR" ]; then
-                echo "Checking for safe prefix in '$BROOT' failed. Should be $SIMPLEBUILD_DIR"
-                exit 1
-            fi
+		if [[ "$broot" =~ $(echo "$path_regex") ]]; then
+			if [ "${BASH_REMATCH[1]}" != "$SIMPLEBUILD_DIR" ]; then
+				echo "Checking for safe prefix in '$BROOT' failed. Should be $SIMPLEBUILD_DIR"
+				exit 1
+			fi
 
-            echo -e "\e[96mDelete previous Source\e[0m"
-            rm -rf "$broot"
-	    
-	    category="${BASH_REMATCH[3]}"
+			echo -e "\e[96mDelete previous Source\e[0m"
+			rm -rf "$broot"
+			
+			category="${BASH_REMATCH[3]}"
 
-            if [ "$(ls -A "$SIMPLEBUILD_DIR/$category")" ]; then
-                echo -e "\e[96mCategory dir is not empty. Keep it\e[0m"
-            else
-                echo -e "\e[96mRemoving empty category directory $SIMPLEBUILD_DIR/$category\e[0m"
-                rmdir "$SIMPLEBUILD_DIR/$category"
-            fi
+			if [ "$(ls -A "$SIMPLEBUILD_DIR/$category")" ]; then
+				echo -e "\e[96mCategory dir is not empty. Keep it\e[0m"
+			else
+				echo -e "\e[96mRemoving empty category directory $SIMPLEBUILD_DIR/$category\e[0m"
+				rmdir "$SIMPLEBUILD_DIR/$category"
+			fi
+		else
+			echo 'path_regex for $BROOT failed'
+			exit 1
+		fi
+	fi
 
-        else
-            echo 'path_regex for $BROOT failed'
-            exit 1
-        fi
-    fi
-    # remove line from bashrc with BROOT
-    sed -i '/BROOT/d' "$SIMPLEBUILD_DIR/bashrc"
+	# remove line from bashrc with BROOT
+	sed -i '/BROOT/d' "$SIMPLEBUILD_DIR/bashrc"
 
-    unset broot path_regex category
+	unset broot path_regex category
 
-    BASH_ENV="$SIMPLEBUILD_DIR/bashrc" su simple -s /bin/bash /usr/lib/simple/all_build -- $CPV -all_build
+	BASH_ENV="$SIMPLEBUILD_DIR/bashrc" su simple -s /bin/bash /usr/lib/simple/all_build -- $CPV -all_build
 
-    /usr/lib/simple/install $CPV
+	/usr/lib/simple/install $CPV
 done
 }
 
